name: website2
channels:
  - javascript
dependencies:
  - python=3.8
  - appdirs
  - email-validator
  - Jinja2
  - Markdown
  - MarkupSafe
  - pip
  - requests
  - SQLAlchemy 
  - WTForms
  - pip --user :
      - dnspython
      - Flask
      - Flask-Blogging
      - Flask-Principal
      - Flask-FlatPages
      - Flask-FileUpload
      - Flask-Bcrypt
      - Flask-Caching
      - Flask-Login
      - Flask-SQLAlchemy
      - Flask-WTF
      - Frozen-Flask
      - setuptools
      - virtualenv
      - Werkzeug
      
